version: "3.8"

services:
  db:
    build: ./database
    restart: always
    ports:
      - "5432:5432"
    hostname: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - postgres
  datos-python:
    build: ./generador-datos
    restart: always
    volumes:
      - ./faker:/usr/src/app
    ports:
      - "3002:3002"
    networks:
      - faker
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - db
      - datos-python
    networks:
      - postgres
      - faker
  frontend:
    build: ./front
    ports:
      - "3009:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      - backend

volumes:
  database_data:
    driver: local
networks:
  postgres:
    driver: bridge
  faker:
    driver: bridge
